/**
 * Every Swedish string the player can see (plan §3.7): du-tilltal, ” ” and –, plain child words.
 * Olov reads every line aloud before a release.
 */
export const sv = {
  title: 'Elof och det stora godisäventyret',
  homeScreen: {
    shortName: 'Elofs äventyr',
    title: 'Lägg till på hemskärmen',
    apple: 'På iPhone och iPad: öppna spelet i Safari, tryck på Dela och välj Lägg till på hemskärmen.',
    android: 'På Android: öppna webbläsarens meny och välj Installera app eller Lägg till på startskärmen.',
    offline: 'Öppna spelet med internet först. Delar som har laddats kan sedan spelas utan internet, så länge enheten har plats att spara dem.',
  },
  painting: {
    title: 'Måla ögonen', hint: 'Följ ringen med fingret eller musen.',
    assist: 'Måla med hjälp', picture: 'Spökets ögon. Följ den prickade ringen.',
    figurePicture: 'Min nya trägubbes ögon. Följ den prickade ringen.',
    tryAgain: 'Dra med penseln, så hjälper Pappa till.', painted: 'Ett öga till liv!',
  },
  carving: {
    title: 'Min första trägubbe', hint: 'Alltid bort från kroppen. Följ pilen.',
    assist: 'Tälj med Pappa', picture: 'Elof sitter till vänster. Dra från handen längs pilen, bort från kroppen.',
    tryAgain: 'Bort från kroppen. Pappa hjälper dig att prova igen.', carved: 'Ett tag med kniven!',
    step: 'Tag {step} av 3',
  },
  sharing: {
    title: 'Dela godiset', choose: 'Välj något gott.', friend: 'Välj en vän.', back: 'Tillbaka',
    bird: 'Lavskrikan får ett lingon ur fickan.', given: 'Har fått', nowFriend: '{sweet} – vem ska få den?',
    thanks: '{friend} fick {sweet}!',
    sweets: { gelehallon: 'Geléhallon', karamell: 'Karamell', skumbanan: 'Skumbanan', lingon: 'Lingon' },
    friends: { tragubbe: 'Trägubben', spoket: 'Spöket', jay: 'Lavskrikan' },
  },
  party: {
    title: 'Godiskalaset', thanks: '{friend} tackar glatt för {sweet}!',
    friends: { mamma: 'Mamma', pappa: 'Pappa', moa: 'Moa', bertil: 'Bertil', spoket: 'Spöket' },
  },

  // The two action buttons. Använd will show the specific verb once there is something to do.
  hop: 'Hoppa',
  act: 'Använd',
  // The button that calls the helper: a ghost portrait in Kapitel 1, a jay from Kapitel 2.
  help: 'Hjälp',

  // Shown instead of the on-screen controls when a keyboard or a gamepad is in use.
  keysHint: '← → springa och gunga · Mellanslag hoppa och släppa · ↑ ↓ klättra · E använd · Shift gå',
  padHint: 'Spaken springa, klättra och gunga · A hoppa och släppa · X använd',

  // The tutorial is wordless on screen; these labels also make its pictures available to a screen reader.
  tutorial: {
    keys: { move: '← →', hop: '␣', act: 'E' },
    pad: { move: '✚', hop: 'A', act: 'X' },
    touch: { move: 'För fingret åt sidan för att gå.', hop: 'Tryck på Hoppa.', act: 'Tryck på Använd för att ta stjärnan.' },
    // Spoken descriptions use the same controls as the key reference.
    keyboard: { move: 'Gå med vänster och höger piltangent.', hop: 'Hoppa med mellanslag.', act: 'Ta stjärnan med E.' },
    gamepad: { move: 'Gå med vänster spak eller styrkorset.', hop: 'Hoppa med A.', act: 'Ta stjärnan med X.' },
  },

  // What Använd says when there is something to use: one word for each thing Elof can do.
  verbs: {
    slide: 'Åk ner',
    lace: 'Kasta snöret',
    push: 'Knuffa',
    pull: 'Dra',
    turn: 'Vänd',
    take: 'Ta',
    call: 'Ropa',
    callMoa: 'Ropa på Moa',
    gardenBoard: 'Kliv på planet',
    gardenGiveDrawing: 'Visa Moa teckningen',
    callPappa: 'Ropa på Pappa',
    callBertil: 'Ropa på Bertil',
    callMamma: 'Ropa på Mamma',
    takeLight: 'Ta lysklubban',
    climbOn: 'Kliv upp',
    board: 'Kliv på',
    lift: 'Lyft',
    lowerLace: 'Sänk snöret',
    paintEyes: 'Måla ögon',
    takeBag: 'Ta påsen',
    giveTragubbe: 'Ge trägubben',
    giveGhost: 'Ge spöket',
    giveJay: 'Ge lavskrikan',
    taste: 'Smaka',
    goHome: 'Gå hem',
    paintGhost: 'Måla ögonen!',
    giveMamma: 'Ge Mamma',
    givePappa: 'Ge Pappa',
    giveMoa: 'Ge Moa',
    giveBertil: 'Ge Bertil',
    takeKnife: 'Ta kniven',
    carve: 'Tälj',
    brush: 'Borsta tänderna',
    give: 'Ge',
    pick: 'Plocka',
    leaveBerry: 'Lämna ett lingon',
    rideAnts: 'Åk med myrorna',
    standOn: 'Ställ dig här',
    grab: 'Ta!',
  },

  // Who a bubble belongs to. The ghost is "spöket" until Elof names it in the epilogue.
  who: {
    mamma: 'Mamma',
    pappa: 'Pappa',
    moa: 'Moa',
    bertil: 'Bertil',
    elof: 'Elof',
    spoket: 'Spöket',
  },
  ghostName: 'Klonk',
  giveKlonk: 'Ge Klonk',
  storyContext: {
    now: 'Just nu', recap: 'Vårt äventyr', family: 'Vi hjälps åt',
    welcomeMemory: 'Spöket ville ha ett välkommen-hem-kalas för min gamla trägubbe.',
    welcomeFigure: 'Spöket tog godiset för att välkomna trägubben hem!',
    recovered: 'Upphittat godis', recoveredCount: 'Upphittat godis: {count}. Öppna albumet.',
    purposes: {
      paint: { purpose: 'Måla Pappas nya träspöke.', recap: 'Det är lördagsmorgon. Träspöket väntar på sina ögon.' },
      paintSecond: { purpose: 'Måla spökets andra öga.', recap: 'Ett öga är klart. Nu målar jag det andra.' },
      awakening: { purpose: 'Titta – spöket blinkar!', recap: 'Jag gav träspöket ögon. Nu verkar det vakna.' },
      chase: { purpose: 'Följ spöket – det har min påse.', recap: 'Spöket vaknade och tog min lördagsgodispåse!' },
      starTrail: { purpose: 'Följ spöket och godisspåret.', recap: 'Påsen har gått sönder. Godiset visar vart spöket sprang.' },
      tiny: { purpose: 'Familjen är här hos mig.', recap: 'Stjärnan gjorde mig lika liten som spöket. Familjen såg det.' },
      hand: { purpose: 'Kliv upp i Pappas hand.', recap: 'Jag krympte. Pappa sträcker fram handen åt mig.' },
      handoff: { purpose: 'Följ godisspåret ut på gården.', recap: 'Spöket har påsen. Jag kan följa det där de stora inte når.' },
      garden: { purpose: 'Följ spöket. Hitta min påse.', recap: 'Jag samlar upp godiset längs spåret. Spöket har resten.' },
      gardenMemory: { purpose: 'Följ spöket mot Moa.', recap: 'Ett minne visade Pappa, mig som liten och en trägubbe.' },
      moa: { purpose: 'Ropa på Moa vid roten.', recap: 'Spöket har smitit in där en stor hand inte når.' },
      planeBoard: { purpose: 'Kliv på Moas pappersplan.', recap: 'Moa har gjort planet klart. Jag bestämmer när vi lyfter.' },
      plane: { purpose: 'Flyg med Moas pappersplan.', recap: 'Moa hjälper mig till skogen. Godisspåret fortsätter där.' },
      gardenPocket: { purpose: 'Jag kan hämta Moas lövteckning.', recap: 'Planet väntar. Slangen går ner under spånbron, om jag vill leta.' },
      gardenDrawing: { purpose: 'Hitta lövteckningen under bron.', recap: 'Moa tappade sin teckning här. Slangen tar mig tillbaka upp.' },
      gardenClimb: { purpose: 'Klättra upp längs slangen.', recap: 'Jag hittade Moas lövteckning. Nu kan jag komma tillbaka till henne.' },
      gardenReturnDrawing: { purpose: 'Jag kan visa Moa lövteckningen.', recap: 'Planet är klart att lyfta. Jag kan också hjälpa Moa få tillbaka sin teckning.' },
      forest: { purpose: 'Följ godisspåret genom skogen.', recap: 'Spöket är framför mig. Jag samlar upp godiset längs vägen.' },
      forestDoor: { purpose: 'Följ spöket vidare genom skogen.', recap: 'Spöket gav godis vid en liten dörr. Varför gjorde det så?' },
      vittraClue: { purpose: 'Följ spöket vidare genom skogen.', recap: 'Vid dörren kom ett tack – och en bild att fundera på.' },
      jay: { purpose: 'Ge lavskrikan ett lingon.', recap: 'Lavskrikan vill följa med. Ett lingon kan bli en vänskap.' },
      seesaw: { purpose: 'Ropa på Pappa vid ravinen.', recap: 'Här är för långt att hoppa. Pappa kan bygga en väg över.' },
      cone: { purpose: 'Rulla kotten till gungbrädan.', recap: 'Pappa har gjort en gungbräda. Kotten kan skjuta iväg mig.' },
      coneTrial: { purpose: 'Prova gungbrädan med lilla kotten.', recap: 'Den lilla kotten är på plats. Hur högt kan den skjuta mig?' },
      coneRetry: { purpose: 'Rulla den stora kotten till Pappa.', recap: 'Den lilla kotten gav ett kort hopp. En större behövs.' },
      launch: { purpose: 'Ställ dig på gungbrädan.', recap: 'Kotten är på plats. Nu hjälper Pappa mig över ravinen.' },
      cap: { purpose: 'Ropa på Bertil vid bäcken.', recap: 'Spöket är på andra sidan. Bertils keps kan bli min båt.' },
      capRide: { purpose: 'Åk över bäcken i Bertils keps.', recap: 'Bertil hjälper mig över vattnet och går längs stranden.' },
      eddy: { purpose: 'Dra upp spöket ur virveln!', recap: 'Spöket sitter fast i vattnet. Nu behöver det min hjälp.' },
      waiting: { purpose: 'Följ spöket som väntar på mig.', recap: 'Jag räddade spöket. Nu väntar det och visar ett berg.' },
      bog: { purpose: 'Följ spöket över myren.', recap: 'Spöket flyr inte som förut. Vart vill det att jag ska gå?' },
      mamma: { purpose: 'Ropa på Mamma vid vattnet.', recap: 'En stor pöl stoppar mig. Mamma kan hjälpa mig över.' },
      braid: { purpose: 'Ropa på Mamma vid spången.', recap: 'Spången är högt ovanför mig. Mamma kan låna ut sin fläta.' },
      light: { purpose: 'Ta spökets lysklubba.', recap: 'Spöket har lämnat ett ljus till mig. Det hjälper i dimman.' },
      mist: { purpose: 'Följ ljuset genom dimman.', recap: 'Lysklubban visar vägen mellan tuvorna.' },
      chick: { purpose: 'Led tranungen till sin familj.', recap: 'En liten trana har kommit bort. Den följer mitt ljus.' },
      pine: { purpose: 'Följ spöket mot berget.', recap: 'Tranungen är hemma. Spöket visar en tall och en spricka.' },
      crane: { purpose: 'Flyg med tranan till berget.', recap: 'Vi hjälpte tranungen hem. Nu får jag skjuts uppåt.' },
      bogLantern: { purpose: 'Jag kan gå tillbaka till gläntan.', recap: 'Spången leder till platsen där jag hittade lysklubban. Tranan väntar på mig.' },
      bogReturn: { purpose: 'Gå tillbaka till tranan när jag vill.', recap: 'Jag kom tillbaka till gläntan. Spången går åt båda hållen.' },
      mountain: { purpose: 'Följ spöket uppför berget.', recap: 'Spöket väntar längre upp. Jag vill förstå vad det visar.' },
      lift: { purpose: 'Hjälp spöket uppför klippan.', recap: 'Påsen är för tung för spöket. Tillsammans kommer vi upp.' },
      tall: { purpose: 'Följ snöret till den gamla tallen.', recap: 'Jag hjälpte spöket upp. Det visar vägen vidare.' },
      mountainReturn: { purpose: 'Välj snöret eller hyllorna ner.', recap: 'Jag hittade godiset på röset. Snöret är en lugn väg ner till stigen vid tallen.' },
      figure: { purpose: 'Hämta hem min första trägubbe.', recap: 'Minnet visade min gamla trägubbe, ensam i en spricka.' },
      crack: { purpose: 'Hjälp spöket vid sprickan.', recap: 'Spöket visar att någon väntar där nere.' },
      pull: { purpose: 'Dra upp trägubben med snöret.', recap: 'Snöret är nere. Vi kan hjälpa den som sitter fast.' },
      eyes: { purpose: 'Ge trägubben nya ögon.', recap: 'Vi fick upp en ensam trägubbe. Dess gamla ögon är borta.' },
      bag: { purpose: 'Ta tillbaka min godispåse.', recap: 'Trägubben har nya ögon. Spöket räcker tillbaka påsen.' },
      share: { purpose: 'Dela godiset med mina vänner.', recap: 'Påsen är tillbaka. Nu väljer jag vem som får vad.' },
      welcome: { purpose: 'Ordna ett välkommen-hem-kalas.', recap: 'Spöket tog godiset för att välkomna min gamla trägubbe hem!' },
      gold: { purpose: 'Smaka mitt gyllene geléhallon.', recap: 'Vi har delat godiset. Geléhallonet glittrar som stjärnan.' },
      reunion: { purpose: 'Möt familjen under norrskenet.', recap: 'Godiset gjorde mig stor igen. Påsen är tillbaka.' },
      home: { purpose: 'Följ familjen hem.', recap: 'Vi tar hem båda trägubbarna till hyllan.' },
      party: { purpose: 'Dela lördagsgodiset med familjen.', recap: 'Vi är hemma igen. Alla får vara med på godiskalaset.' },
      carveStart: { purpose: 'Hitta Pappa och lär dig tälja.', recap: 'Alla har fått godis. Nu vill jag göra en egen trägubbe.' },
      carve: { purpose: 'Tälj min trägubbe med Pappa.', recap: 'Pappa hjälper min hand. Jag täljer alltid bort från kroppen.' },
      paintOwn: { purpose: 'Måla min trägubbes två ögon.', recap: 'Jag har täljt min första figur. Nu får den sina ögon.' },
      teeth: { purpose: 'Borsta tänderna före läggdags.', recap: 'Min trägubbe står i fönstret. Nu är det dags för sängen.' },
      bed: { purpose: 'Gå och lägg dig.', recap: 'Ett helt äventyr får plats i vårt godiskalas.' },
      village: { purpose: 'Gå till godisbutiken med min vän.', recap: 'En lördag senare gör vi en ny liten utflykt tillsammans.' },
      shop: { purpose: 'Gå in i butiken och hitta påsen.', recap: 'Vi har kommit fram. Där inne väntar godis att dela.' },
      shopDone: { purpose: 'Hämta en påse att dela på.', recap: 'Vi handlar tillsammans. Sedan går vi hem igen.' },
    },
    helpers: {
      home: 'Pappa hjälper mig måla. Familjen är här hemma.',
      trail: 'Familjen följer den stora stigen. Jag följer det lilla spåret.',
      moa: 'Moa gör ett pappersplan. De stora tar vägen runt.',
      forest: 'Pappa hjälper vid ravinen. Bertil väntar vid bäcken.',
      pappa: 'Pappa bygger gungbrädan. Jag hjälper till med kotten.',
      bertil: 'Bertil lånar ut sin keps och följer mig från stranden.',
      bog: 'Mamma hjälper vid vattnet och följer spången ovanför mig.',
      bogLoop: 'Mamma har lagt en spång. Tranan väntar vid sin familj.',
      mountain: 'Familjen följer stigen upp. Spöket och jag hjälps åt här.',
      reunion: 'Nu är familjen hos mig igen. Vi går hem tillsammans.',
      carving: 'Pappa hjälper min hand. Alla är nära mig.',
      village: 'Min vän följer med. Vi hjälper varandra längs gatan.',
    },
    loopRecaps: {
      bogBuilding: 'Mamma lägger en spång tillbaka. Jag kan fortsätta till tranan under tiden.',
      bogReady: 'Mammas spång leder till gläntan där jag hittade ljuset, om jag vill gå dit.',
      bogReturned: 'Jag gick tillbaka till gläntan. Mammas spång låter mig välja väg.',
    },
    handoffs: {
      prolog: { title: 'Ut på gården', text: 'Spöket har min påse, med guldgodiset i. Jag följer godisspåret, och familjen går den stora vägen bredvid.' },
      garden: { title: 'Vidare till granskogen', text: 'Moas plan tar mig till skogen. De stora följer stigen runt.' },
      gardenClue: { title: 'Godisspåret leder till skogen', text: 'Spöket är längre fram. Familjen följer stigen runt.' },
      granskog: { title: 'Spöket väntar på mig', text: 'Jag hjälpte det ur vattnet. Nu visar det vägen mot myren.' },
      granskogClue: { title: 'Vidare mot myren', text: 'Godisspåret fortsätter förbi bäcken. Familjen följer stigen.' },
      myren: { title: 'Upp mot berget', text: 'Tranungen är hemma. Tranan ger mig skjuts, och familjen följer stigen.' },
      myrenClue: { title: 'Vidare mot berget', text: 'Spöket väntar längre upp. Jag vill förstå vad det visar.' },
      berget: { title: 'Min trägubbe väntar', text: 'Minnet visade var den försvann. Nu hämtar spöket och jag hem den.' },
      bergetClue: { title: 'Vid den gamla tallen', text: 'Spöket visar en spricka. Vi behöver ta reda på vad som finns där.' },
      norrsken: { title: 'Hem till godiskalaset', text: 'Trägubben är räddad och påsen är tillbaka. Nu går vi hem tillsammans.' },
      norrskenOrigin: { title: 'Hem till godiskalaset', text: 'Pappa täljde trägubben åt mig när jag var liten. Vi tappade den här på berget. Spöket tog godiset för att välkomna den hem.' },
      norrskenClue: { title: 'Tillsammans på berget', text: 'Spöket och jag har följt samma väg. Familjen är nära.' },
      epilog: { title: 'Ett äventyr att minnas', text: 'Vi delade godiset och hjälptes åt. Det finns fler små saker att upptäcka.' },
      epilogClue: { title: 'Fler små äventyr', text: 'Familjen är hemma. Här finns fler små saker att upptäcka tillsammans.' },
      byn: { title: 'Hem med något att dela', text: 'Vi har varit i godisbutiken tillsammans. Nu väntar vägen hem.' },
    },
  },
  memories: {
    title: 'Pappas minnen',
    watch: 'Se minnet igen',
    waiting: 'Ett minne att hitta',
    next: 'Nästa bild',
    back: 'Tillbaka',
  },

  // Words a scene lays over the picture (src/ui/scene.ts): a time of day as a part of the story opens, and the title.
  scene: {
    morning: 'Lördagsmorgon',
    // Each chapter's time card: where, and the time of day (plan §4.9).
    garden: 'Gården · klockan tio',
    granskog: 'Granskogen · halv tolv',
    myren: 'Myren · halv fem',
    berget: 'Berget · klockan sex',
    norrsken: 'Norrskenet · i skymningen',
    epilog: 'Godiskalaset · klockan nio',
    title: 'Elof och det stora godisäventyret',
  } as Record<string, string>,

  // What is said, in bubbles: the game has no voices. At most about 40 characters each (plan §3.7).
  lines: {
    // The extra chapter, Byn: a Saturday later, on the way to the candy shop.
    // At the party, when what he found under the deck is given back (plan §4.8).
    clipBack: 'Mitt hårspänne! Tack, lillebror!',
    marbleBack: 'Kula! Min kula!',
    coinBack: 'En krona! Den får du behålla.',
    cobbles1: 'Stenarna på berget var en strand.',
    cobbles2: 'Havet nådde ända dit en gång.',
    cobbles3: 'Vågorna gjorde dem runda.',
    again: 'En stjärna till. Nu handlar vi!',
    lake: 'En sjö! Mitt på gatan.',
    shop: 'Framme! Det luktar godis.',
    shopInside: 'Godiset är större än jag!',
    shopBag: 'En påse att dela på!',
    stomp: 'Ge tillbaka mitt godis!',
    tiny: 'Lillebror?! Du är ju pytteliten!',
    rootFingers: 'Där kröp spöket in. Jag får inte plats!',
    gardenReady: 'Planet väntar. Vi lyfter när du vill.',
    gardenPocket: 'Min lövteckning föll under spånbron!',
    gardenFound: 'En lövteckning! Den är Moas.',
    gardenThanks: 'Du hittade den! Vi hjälps åt, lillebror.',
    givesAway: 'Spöket ger bort mitt godis!?',
    vittraBerry: 'Ett lingon till er också.',
    forestVittraClue: 'En liten bild från vittrorna.',
    forestTrial: 'Oj! Nästan. Den större väger mer.',
    heja: 'Heja lillebror!',
    thanked: 'Spöket tackade mig!',
    spangen: 'På myren går vi på spången.',
    bogChickLight: 'Följ mitt ljus hem till din familj.',
    bogFamilyHome: 'Ungen är hemma. Vill du ha en spång?',
    bogBridgeReady: 'Över dimman, och tillbaka igen.',
    bogLightReturn: 'Nu går spången åt båda hållen!',
    fetch: 'Spöket vill hämta hem min trägubbe!',
    mountainLoop: 'Snöret runt röset. En väg ner!',
    // Pappa on the summit: one thing said, in four bubbles.
    first1: 'Min allra första trägubbe …',
    first2: 'Den täljde jag till dig',
    first3: 'när du var liten, Elof.',
    first4: 'Vi tappade den här uppe.',
    // The prologue and the epilogue.
    newGhost: 'Jag har täljt ett spöke. Måla ögonen!',
    // The prologue as it is told now (docs/narrative-audit.md): a cosy morning, the ghost wakes, Elof shrinks.
    notYet: 'Bertil! Godiset öppnar vi ikväll.',
    jayWindow: 'Titta! En lavskrika!',
    dropped: 'Hoppsan! Vem tappade spöket?',
    sameSize: 'Jag är lika liten som spöket!',
    hurt: 'Gör det ont?',
    sawGlitter: 'Jag såg det! Påsen började glittra.',
    goldHope: 'Guldgodiset kan göra dig stor igen.',
    onlyWood: 'Det är ju bara trä.',
    snuck: 'Det smiter!',
    nearYou: 'Vi är nära dig hela tiden.',
    mapForYou: 'Jag ritar en karta åt dig!',
    followTrail: 'Följ godisspåret, Elof.',
    stolenBag: 'Pappa! Spöket tog min godispåse!',
    fallenStar: 'En stjärna föll ur påsen!',
    tinyElof: 'Stjärnan gör dig liten. Vi hjälper dig!',
    klonk: 'Klonk, klonk!',
    named: 'Du ska heta Klonk!',
    away: 'Alltid bort från kroppen.',
    carved: 'Jag kan tälja!',
  },

  // The sixteen kinds of hidden candy (plan §4.3): plain names of sorts, never a brand.
  kinds: {
    gelehallon: 'Geléhallon',
    gummibjorn: 'Gummibjörn',
    skumbanan: 'Skumbanan',
    skumsvamp: 'Skumsvamp',
    sockerbit: 'Sockerbit',
    gummiorm: 'Gummiorm',
    chokladkola: 'Chokladkola',
    colaflaska: 'Colaflaska',
    chokladpeng: 'Chokladpeng',
    stektagg: 'Stekt ägg',
    surnapp: 'Sur napp',
    lakritskonfekt: 'Lakritskonfekt',
    polkagris: 'Polkagris',
    graddkola: 'Gräddkola',
    salmiakruta: 'Salmiakruta',
    chokladpralin: 'Chokladpralin',
  } as Record<string, string>,
  // Said at the top of the screen when a new kind is found, and under the stickers on a chapter's card.
  found: 'Ny sort: {name}!',
  stickers: 'Gömt godis',
  // Hittegods (plan §4.8): the small things lost under the deck. Said at the top of the screen when he
  // finds one, and shown in the album. Plain things, and never a brand.
  lost: { marble: 'Bertils kula', clip: 'Moas hårspänne', brick: 'En leksakskloss', coin: 'En krona' } as Record<string, string>,
  lostFound: 'Du hittade något: {name}!',
  lostTitle: 'Hittegods',
  // Daggklockspelet (plan §4.8): said when the drops play the opening theme in order.
  dewSong: 'Hela gräsmattan glittrar!',
  keepsakes: 'Små minnen',
  vittraSticker: 'Vittrornas tack',
  vittraFound: 'Ett klistermärke! Tack för lingonet.',
  // The album in the pause panel: every kind, found or not.
  album: { title: 'Godisalbumet', count: '{found} av {total} sorter', golden: 'Det gyllene geléhallonet', goldenFound: 'Alla sorter! Ett geléhallon i guld.' },
  photos: {
    title: 'Foton', journey: 'Vårt äventyr', empty: 'Här samlas bilder från ditt äventyr.',
    open: 'Titta på {name}', previous: 'Förra', next: 'Nästa', back: 'Tillbaka', done: 'Klart',
    count: '{n} av {total}', thanks: 'Tack för äventyret!', again: 'Se äventyret igen',
    credits: 'Spöket är täljt av Pappa Emil. Spelet är gjort till Elof av morbror Olov – med hjälp av Claude och Codex.',
    moments: {
      shrinking: 'Liten som en godis', swing: 'Första svingen', plane: 'Moas flygplan', cap: 'Bertils kepsbåt',
      crane: 'På tranans rygg', aurora: 'Under norrskenet', carving: 'Min första trägubbe',
    },
  },
  explore: {
    title: 'Utforska vidare',
    hint: 'Välj en plats. Allt du har hittat finns kvar.',
    routeFound: 'Utmaningsgodiset hittat',
    routeWaiting: 'En utmaningsväg att utforska',
    chapters: { prolog: 'Lördagsmorgon', garden: 'Gården', granskog: 'Granskogen', myren: 'Myren', berget: 'Berget', norrsken: 'Norrskenet', epilog: 'Godiskalaset', byn: 'Byn' } as Record<string, string>,
    icons: { prolog: '☀', garden: '❀', granskog: '♧', myren: '≈', berget: '△', norrsken: '✧', epilog: '⌂', byn: '⌂' } as Record<string, string>,
  },

  // The card at a chapter's end.
  end: {
    chapter: 'Kapitel {n} klart!',
    // A part of the story with a name of its own, by its id.
    named: { prolog: 'Lördagsmorgon', norrsken: 'Finalen klar!', epilog: 'Slut', byn: 'Byn klar!' } as Record<string, string>,
    // The last card of the story, in place of "Fortsättning följer!".
    closing: {
      epilog: 'Klonk kunde inte säga det med ord. Men Elof förstod.',
      byn: 'Lördagsgodiset är köpt. Nu går vi hem.',
    } as Record<string, string>,
    // On the story's last card, the button to an extra chapter.
    bonus: 'Ett kapitel till',
    window: 'Elofs lilla trägubbe står i månljuset. Dess målade ögon blinkar.',
    course: 'Framme!',
    next: 'Fortsättning följer!',
    onward: 'Nästa kapitel',
    again: 'Spela igen',
    candy: 'godisar i påsen',
  },

  // A memory has no words. This is what a screen reader says while its pictures are shown.
  memory: 'Ett minne',

  // Moas karta: a child's names for the places, as she would write them.
  map: {
    title: 'Moas karta',
    unfinished: 'Här ritar Moa fortfarande …',
    home: 'Hemma',
    forest: 'Granskogen',
    brook: 'Bäcken',
    bog: 'Myren',
    mountain: 'Berget',
    here: 'Här är du',
  },

  // The candy bag in the corner. Screen readers hear the name and then the number.
  bag: 'Upphittat godis · öppna albumet',

  // Chapter codes (plan §6.9): three plain words that open a chapter's start on another device. No names.
  codes: {
    garden: ['DAGG', 'SNÖRE', 'BRÄDA'],
    granskog: ['GRAN', 'KOTTE', 'MOSSA'],
    myren: ['TUVA', 'SPÅNG', 'TRANA'],
    berget: ['TALL', 'STEN', 'VIND'],
    norrsken: ['TOPP', 'KVÄLL', 'STJÄRNA'],
    epilog: ['KNIV', 'SPÅN', 'LÖRDAG'],
    byn: ['GATA', 'LÖV', 'CYKEL'],
  } as Record<string, readonly [string, string, string]>,
  code: {
    // On a chapter's card, over the next chapter's three words.
    next: 'Kod till nästa kapitel',
    // On the title.
    have: 'Jag har en kod',
    hint: 'Skriv de tre orden',
    open: 'Öppna',
    wrong: 'Den koden finns inte. Titta på kortet en gång till!',
  },

  // The title and the first start.
  start: {
    begin: 'Börja',
    resume: 'Fortsätt',
    over: 'Börja om från början',
    how: 'Hur vill du spela?',
    rotate: 'Vänd skärmen på bredden!',
  },

  players: {
    choose: 'Byt spelare', new: 'Ny spelare', name: 'Vad vill du heta?',
    local: 'Namnet stannar på den här enheten. Alla spelar som Elof.',
    next: 'Välj spelsätt', back: 'Tillbaka', settings: 'Inställningar',
    remove: 'Ta bort {name}', removeAsk: 'Ta bort {name} och allt som spelaren har sparat?',
    restartAsk: 'Börja om från början för {name}? Godis, bilder och framsteg tas bort.',
    yes: 'Ja', no: 'Nej, gå tillbaka', unreadable: 'Kan inte läsas',
    error: 'Det gick inte att spara ändringen. Försök igen.',
    indexUnreadable: 'Spelarlistan gick inte att läsa. Det sparade finns kvar. Prova att ladda om sidan.',
    preserved: 'Det sparade spelet gick inte att läsa. Det finns kvar. Välj en annan spelare eller börja om.',
  },

  // The pause panel. Every button has a picture beside its word, for a child who can't read yet.
  pause: {
    open: 'Paus',
    title: 'Paus',
    resume: 'Spela vidare',
    home: 'Till startsidan',
    close: 'Stäng',
    style: 'Spelsätt',
    aventyr: 'Äventyr',
    aventyrHint: 'Du hoppar och gungar själv.',
    lugnt: 'Lugnt',
    lugntHint: 'Spelet hjälper dig med hopp och gungor.',
    swingHelp: 'Hjälp med svingen',
    easyJumps: 'Lätta hopp',
    followFinger: 'Följ fingret',
    vibration: 'Vibration vid landning',
    fullscreen: 'Helskärm',
    exitFullscreen: 'Lämna helskärm',
    fullscreenFailed: 'Helskärm kunde inte öppnas. Du kan spela vidare här.',
    followHint: 'Håll fingret dit du vill gå. Släpp för att stanna.',
    graphics: 'Grafik',
    graphicsAuto: 'Auto',
    graphicsLow: 'Låg',
    graphicsMid: 'Mellan',
    graphicsHigh: 'Hög',
    graphicsHint: 'Auto väljer åt dig. Låg gör bilden enklare.',
    graphicsFallback: 'Den här enheten använder Låg.',
    slower: 'Lugnare tempo',
    sound: 'Ljud',
    music: 'Musik',
    effectsVolume: 'Ljudvolym',
    musicVolume: 'Musikvolym',
    effectsQuieter: 'Sänk ljudvolymen',
    effectsLouder: 'Höj ljudvolymen',
    musicQuieter: 'Sänk musikvolymen',
    musicLouder: 'Höj musikvolymen',
    loud: 'Ljud även i tyst läge',
    lefty: 'Vänsterhänt',
    bigText: 'Större text',
    calm: 'Mindre rörelse',
    // How much the helper does by itself (plan §4.6).
    help: 'Hjälp',
    helpAsk: 'Bara när jag frågar',
    helpRemind: 'Påminn mig',
    helpGuide: 'Guida mig',
    stuck: 'Jag har fastnat',
    stuckAsk: 'Tillbaka till den stora godisbiten?',
    stuckYes: 'Ja, tillbaka',
    stuckNo: 'Nej, spela vidare',
  },

  controls: {
    title: 'Tangenter och handkontroll',
    back: 'Tillbaka till paus',
    keyboard: 'Tangentbord',
    gamepad: 'Handkontroll',
    keyboardRows: [
      ['← → / A D', 'Springa och gunga'],
      ['Shift + ← → / A D', 'Gå långsamt'],
      ['Mellanslag / ↑ / W', 'Hoppa. Håll för högre hopp.'],
      ['↑ ↓ / W S', 'Klättra på slang och snöre'],
      ['Mellanslag', 'Släpp gungan'],
      ['E / Enter', 'Använd det som är nära'],
      ['H', 'Ropa på hjälparen'],
      ['G', 'Öppna godisalbumet'],
      ['Esc / P', 'Paus'],
      ['Tab / Enter / Esc', 'Välj / tryck / tillbaka i menyer'],
    ],
    gamepadRows: [
      ['Spaken / styrkorset', 'Springa, klättra och gunga'],
      ['A', 'Hoppa och släpp. Håll för högre hopp.'],
      ['X', 'Använd det som är nära'],
      ['Y', 'Ropa på hjälparen'],
      ['View', 'Öppna godisalbumet'],
      ['Start', 'Paus'],
      ['Spaken / styrkorset', 'Välj i menyer'],
      ['A / B', 'Tryck / tillbaka i menyer'],
    ],
  },

  // Saving (Sköldhästen's wording).
  saveOff: 'Spelet kan inte sparas i den här webbläsaren – men du kan spela ändå.',
  saveUnreadable: 'Det sparade spelet gick inte att läsa.',
  startOver: 'Börja om från början',

  // Stage 0a's test course.
  goal: 'Framme!',

  // Sköldhästen's wording.
  noWebGL: 'Den här webbläsaren kan tyvärr inte visa spelet.',
  loadFailed: 'Något gick fel när spelet laddades.',
  contextLost: 'Bilden försvann en stund. Spelet är pausat och det du har gjort är sparat.',
  contextRestored: 'Bilden är tillbaka. Fortsätt när du är redo!',
  contextReloading: 'Vi hämtar tillbaka bilden. Spelet väntar.',
  recoveryTitle: 'Spelet väntar',
  retry: 'Försök igen',
} as const;
